services:
  ecom-db:
    image: postgres:15
    container_name: ecom-postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/bustle/spot

  ecom-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom_fastapi_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    depends_on:
      - ecom-db



volumes:
  postgres_data: